import { StyleSheet } from 'react-native';
const style = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F1EB',
    width: '100%',
    height: '100%',
    justifyContent: 'space-between',
    paddingTop: 56,
    paddingBottom: 56,
  },
  header: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    width: '100%',
    height: 63,
    paddingLeft: 24,
    paddingRight: 24,
    paddingTop: 10,
    gap: 10,
  },
  title: {
    fontSize: 26,
    fontWeight: '900',
    color: '#1A6B3C',
    fontFamily: 'Lora-Regular',
    lineHeight: 20,
  },
  subtitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1A6B3C',
    fontFamily: 'Cairo-Regular',
    lineHeight: 32,
  },
  textContainer: {
    // for the text labels inside the header in the Welcome screen
    flexDirection: 'column',
    alignItems: 'flex-end', // For Arabic (right aligned)
    width: '100%',
    height: 45,
  },
  palmTreeLogo: {
    width: 54,
    height: 53,
    resizeMode: 'contain',
    textAlign: 'right',
  },
  content: {
    flex: 1,
    justifyContent: 'center',
    width: '100%',
    height: 323,
    gap: 40,
  },
  welcomeTextContainer: {
    width: '100%',
    height: 67,
    paddingLeft: 24,
    paddingRight: 24,
    gap: 12,
    flexDirection: 'column',
    alignItems: 'flex-end', // For Arabic (right aligned)
  },
  welcomeText: {
    width: 342,
    height: 30,
    lineHeight: 30,
    fontSize: 24,
    fontWeight: '600',
    textAlign: 'right',
    fontFamily: 'Cairo-Regular',
  },
  subText: {
    width: 342,
    height: 25,
    lineHeight: 24.5,
    fontSize: 14,
    color: '#797A7B',
    textAlign: 'right',
    fontWeight: '400',
    fontFamily: 'NotoSansArabic_Condensed-Regular',
  },
  cardsContainer: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: 216,
    gap: 16,
  },
  card: {
    borderWidth: 1,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 24,
    width: 342,
    height: 100,
    gap: 10,
    borderColor: '#B1B2B2',
  },
  cardTextWrap: { flex: 1 },
  cardTitle: {
    fontSize: 18,
    fontWeight: '600',
    textAlign: 'right',
    fontFamily: 'Cairo-Regular',
  },
  cardSubtitle: {
    fontSize: 12,
    color: '#797A7B',
    textAlign: 'right',
    fontFamily: 'NotoSansArabic_Condensed-Regular',
  },
  footer: {
    gap: 10,
    width: '100%',
    height: 50,
    paddingLeft: 24,
    paddingRight: 24,
  },
  footerText: {
    width: 342,
    height: 50,
    fontSize: 14,
    color: '#797A7B',
    textAlign: 'center',
    fontFamily: 'NotoSansArabic_Condensed-Regular',
    fontWeight: '400',
    lineHeight: 24.5,
  },
  fotterLink: { color: '#1A6B3C', textDecorationLine: 'none' },
});

export default style;
